create table Player(
    id bigint primary key generated by default as identity,
    balance bigint,
    username varchar(100) not null,
    password varchar(100) not null
);
create table transactionHistory(
    id bigint primary key generated by default as identity,
    player_id bigint references Player(id) on delete set null,
    transaction_name varchar not null
);
insert into Player values (1,'admin','admin1234',0);