create table Player(
    id int primary key generated by default as identity,
    balance int,
    username varchar(100) not null,
    password varchar(100) not null
);
create table transaction_history(
    id int primary key generated by default as identity,
    player_id int references Player(id) on delete set null,
    transaction_name varchar not null
);
insert into Player values (1,'admn','admin1234',0);